inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'test/**/*'
    - 'spec/**/*'
    - 'config/**/*'

Layout/LineLength:
  Enabled: false
